/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

struct _IO_FILE ;
enum _1_fib_$op ;
union _1_fib_$node ;
struct timeval ;
extern int gettimeofday(struct timeval *tv , void *tz ) ;
extern int pthread_cond_broadcast(int *cond ) ;
char **_global_argv  =    (char **)0;
extern int getpagesize() ;
extern int posix_memalign(void **memptr , unsigned int alignment , unsigned int size ) ;
extern int pthread_join(void *thread , void **value_ptr ) ;
extern int open(char const   *filename , int oflag  , ...) ;
extern unsigned int strlen(char const   *s ) ;
extern int pthread_barrier_destroy(int *barrier ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned int maxlen ) ;
extern int pthread_mutex_init(int *mutex , int *attr ) ;
extern int printf(char const   * __restrict  __format  , ...) ;
int _global_argc  =    0;
extern int pthread_cond_signal(int *cond ) ;
extern int pthread_barrier_init(int *barrier , int *attr , unsigned int count ) ;
extern int scanf(char const   *format  , ...) ;
extern int raise(int sig ) ;
char **_global_envp  =    (char **)0;
extern int unlink(char const   *filename ) ;
union _1_fib_$node {
   char _char ;
   unsigned int _unsigned_int ;
   unsigned char _unsigned_char ;
   long _long ;
   unsigned long _unsigned_long ;
   void *_void_star ;
   unsigned short _unsigned_short ;
   unsigned long long _unsigned_long_long ;
   signed char _signed_char ;
   long long _long_long ;
   int _int ;
   short _short ;
};
extern double difftime(long tv1 , long tv0 ) ;
extern int pthread_barrier_wait(int *barrier ) ;
extern int pthread_mutex_lock(int *mutex ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned int size ) ;
extern void *dlsym(void *handle , char *symbol ) ;
extern int gethostname(char *name , unsigned int namelen ) ;
extern void abort() ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern void free(void *ptr ) ;
extern void signal(int sig , void *func ) ;
int main(int argc , char **argv , char **_formal_envp ) ;
extern void exit(int status ) ;
char const   *_1_fib_$strings  =    "";
typedef struct _IO_FILE FILE;
extern int close(int filedes ) ;
extern int mprotect(void *addr , unsigned int len , int prot ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
extern double log(double x ) ;
extern double ceil(double x ) ;
extern int fcntl(int filedes , int cmd  , ...) ;
extern int fclose(void *stream ) ;
extern int pthread_cond_wait(int *cond , int *mutex ) ;
extern void perror(char const   *str ) ;
extern int pthread_cond_init(int *cond , int *attr ) ;
extern int write(int filedes , void *buf , unsigned int nbyte ) ;
extern int ptrace(int request , void *pid , void *addr , int data ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
extern unsigned int strnlen(char const   *s , unsigned int maxlen ) ;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern long clock(void) ;
extern void qsort(void *base , unsigned int nel , unsigned int width , int (*compar)(void *a ,
                                                                                     void *b ) ) ;
extern long time(long *tloc ) ;
extern int rand() ;
extern int read(int filedes , void *buf , unsigned int nbyte ) ;
enum _1_fib_$op {
    _1_fib__Eq_unsigned_int_unsigned_int2int$left_STA_0$result_STA_0$right_STA_1 = 194,
    _1_fib__PlusA_unsigned_int_unsigned_int2unsigned_int$left_STA_0$result_STA_0$right_STA_1 = 102,
    _1_fib__store_unsigned_int$left_STA_0$right_STA_1 = 246,
    _1_fib__Le_unsigned_int_unsigned_int2int$right_STA_0$result_STA_0$left_STA_1 = 128,
    _1_fib__branchIfTrue$expr_STA_0$label_LAB_0 = 241,
    _1_fib__return_unsigned_int$expr_STA_0 = 221,
    _1_fib__load_unsigned_int$left_STA_0$result_STA_0 = 48,
    _1_fib__local$result_STA_0$value_LIT_0 = 38,
    _1_fib__goto$label_LAB_0 = 81,
    _1_fib__constant_unsigned_int$result_STA_0$value_LIT_0 = 213,
    _1_fib__formal$result_STA_0$value_LIT_0 = 14
} ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern int strcmp(char const   *a , char const   *b ) ;
extern double sqrt(double x ) ;
extern int snprintf(char *str , unsigned int size , char const   *format  , ...) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
extern void *malloc(unsigned int size ) ;
extern int nanosleep(int *rqtp , int *rmtp ) ;
extern int pthread_mutex_unlock(int *mutex ) ;
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1), __leaf__)) atoi)(char const   *__nptr )  __attribute__((__pure__)) ;
extern int pthread_create(void *thread , void *attr , void *start_routine , void *arg ) ;
unsigned char _1_fib_$array[1][221]  = { {        _1_fib__constant_unsigned_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_fib__local$result_STA_0$value_LIT_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_fib__store_unsigned_int$left_STA_0$right_STA_1,        _1_fib__constant_unsigned_int$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_fib__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_fib__store_unsigned_int$left_STA_0$right_STA_1,        _1_fib__local$result_STA_0$value_LIT_0,        (unsigned char)8, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_fib__load_unsigned_int$left_STA_0$result_STA_0, 
            _1_fib__local$result_STA_0$value_LIT_0,        (unsigned char)12,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_fib__store_unsigned_int$left_STA_0$right_STA_1,        _1_fib__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_fib__constant_unsigned_int$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_fib__formal$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_fib__load_unsigned_int$left_STA_0$result_STA_0,        _1_fib__Eq_unsigned_int_unsigned_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_fib__branchIfTrue$expr_STA_0$label_LAB_0, 
            (unsigned char)9,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_fib__goto$label_LAB_0,        (unsigned char)25,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_fib__constant_unsigned_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_fib__local$result_STA_0$value_LIT_0,        (unsigned char)16, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_fib__store_unsigned_int$left_STA_0$right_STA_1, 
            _1_fib__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_fib__goto$label_LAB_0,        (unsigned char)136,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_fib__constant_unsigned_int$result_STA_0$value_LIT_0,        (unsigned char)2, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_fib__local$result_STA_0$value_LIT_0, 
            (unsigned char)20,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_fib__store_unsigned_int$left_STA_0$right_STA_1,        _1_fib__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_fib__local$result_STA_0$value_LIT_0,        (unsigned char)20, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_fib__load_unsigned_int$left_STA_0$result_STA_0, 
            _1_fib__formal$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_fib__load_unsigned_int$left_STA_0$result_STA_0,        _1_fib__Le_unsigned_int_unsigned_int2int$right_STA_0$result_STA_0$left_STA_1,        _1_fib__branchIfTrue$expr_STA_0$label_LAB_0, 
            (unsigned char)14,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_fib__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_fib__goto$label_LAB_0,        (unsigned char)75,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_fib__local$result_STA_0$value_LIT_0,        (unsigned char)8, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_fib__load_unsigned_int$left_STA_0$result_STA_0, 
            _1_fib__local$result_STA_0$value_LIT_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_fib__load_unsigned_int$left_STA_0$result_STA_0,        _1_fib__PlusA_unsigned_int_unsigned_int2unsigned_int$left_STA_0$result_STA_0$right_STA_1,        _1_fib__local$result_STA_0$value_LIT_0, 
            (unsigned char)12,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_fib__store_unsigned_int$left_STA_0$right_STA_1,        _1_fib__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_fib__load_unsigned_int$left_STA_0$result_STA_0,        _1_fib__local$result_STA_0$value_LIT_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_fib__store_unsigned_int$left_STA_0$right_STA_1,        _1_fib__local$result_STA_0$value_LIT_0,        (unsigned char)12,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_fib__load_unsigned_int$left_STA_0$result_STA_0,        _1_fib__local$result_STA_0$value_LIT_0, 
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_fib__store_unsigned_int$left_STA_0$right_STA_1,        _1_fib__constant_unsigned_int$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_fib__local$result_STA_0$value_LIT_0,        (unsigned char)20, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_fib__load_unsigned_int$left_STA_0$result_STA_0, 
            _1_fib__PlusA_unsigned_int_unsigned_int2unsigned_int$left_STA_0$result_STA_0$right_STA_1,        _1_fib__local$result_STA_0$value_LIT_0,        (unsigned char)20,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_fib__store_unsigned_int$left_STA_0$right_STA_1,        _1_fib__goto$label_LAB_0, 
            (unsigned char)166,        (unsigned char)255,        (unsigned char)255,        (unsigned char)255, 
            _1_fib__goto$label_LAB_0,        (unsigned char)161,        (unsigned char)255,        (unsigned char)255, 
            (unsigned char)255,        _1_fib__local$result_STA_0$value_LIT_0,        (unsigned char)12,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_fib__load_unsigned_int$left_STA_0$result_STA_0,        _1_fib__local$result_STA_0$value_LIT_0, 
            (unsigned char)16,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_fib__store_unsigned_int$left_STA_0$right_STA_1,        _1_fib__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_fib__local$result_STA_0$value_LIT_0,        (unsigned char)16, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_fib__load_unsigned_int$left_STA_0$result_STA_0, 
            _1_fib__return_unsigned_int$expr_STA_0}};
extern int fseek(struct _IO_FILE *stream ,
                 long offs , int whence ) ;
extern int fscanf(struct _IO_FILE *stream , char const   *format  , ...) ;
void megaInit(void) ;
unsigned int fib(unsigned int n ) ;
void megaInit(void) 
{ 


  {

}
}
int main(int argc , char **argv , char **_formal_envp ) 
{ 
  unsigned int n ;
  int tmp ;
  unsigned int tmp___0 ;
  int _BARRIER_0 ;

  {
  megaInit();
  _global_argc = argc;
  _global_argv = argv;
  _global_envp = _formal_envp;
  _BARRIER_0 = 1;
  if (argc < 2) {
    return (-1);
  }
  tmp = atoi((char const   *)*(argv + 1));
  n = (unsigned int )tmp;
  tmp___0 = fib(n);
  printf((char const   */* __restrict  */)"result: %u\n", tmp___0);
  return (0);
}
}
unsigned int fib(unsigned int n ) 
{ 
  char _1_fib_$locals[24] ;
  union _1_fib_$node _1_fib_$stack[1][32] ;
  union _1_fib_$node *_1_fib_$sp[1] ;
  unsigned char *_1_fib_$pc[1] ;

  {
  _1_fib_$sp[0] = _1_fib_$stack[0];
  _1_fib_$pc[0] = _1_fib_$array[0];
  while (1) {
    switch (*(_1_fib_$pc[0])) {
    case _1_fib__Eq_unsigned_int_unsigned_int2int$left_STA_0$result_STA_0$right_STA_1: 
    (_1_fib_$pc[0]) ++;
    (_1_fib_$sp[0] + -1)->_int = (_1_fib_$sp[0] + 0)->_unsigned_int == (_1_fib_$sp[0] + -1)->_unsigned_int;
    (_1_fib_$sp[0]) --;
    break;
    case _1_fib__load_unsigned_int$left_STA_0$result_STA_0: 
    (_1_fib_$pc[0]) ++;
    (_1_fib_$sp[0] + 0)->_unsigned_int = *((unsigned int *)(_1_fib_$sp[0] + 0)->_void_star);
    break;
    case _1_fib__store_unsigned_int$left_STA_0$right_STA_1: 
    (_1_fib_$pc[0]) ++;
    *((unsigned int *)(_1_fib_$sp[0] + 0)->_void_star) = (_1_fib_$sp[0] + -1)->_unsigned_int;
    _1_fib_$sp[0] += -2;
    break;
    case _1_fib__return_unsigned_int$expr_STA_0: 
    (_1_fib_$pc[0]) ++;
    return ((_1_fib_$sp[0] + 0)->_unsigned_int);
    break;
    case _1_fib__local$result_STA_0$value_LIT_0: 
    (_1_fib_$pc[0]) ++;
    (_1_fib_$sp[0] + 1)->_void_star = (void *)(_1_fib_$locals + *((int *)_1_fib_$pc[0]));
    (_1_fib_$sp[0]) ++;
    _1_fib_$pc[0] += 4;
    break;
    case _1_fib__goto$label_LAB_0: 
    (_1_fib_$pc[0]) ++;
    _1_fib_$pc[0] += *((int *)_1_fib_$pc[0]);
    break;
    case _1_fib__formal$result_STA_0$value_LIT_0: 
    (_1_fib_$pc[0]) ++;
    switch (*((int *)_1_fib_$pc[0])) {
    case 0: 
    (_1_fib_$sp[0] + 1)->_void_star = (void *)(& n);
    break;
    }
    (_1_fib_$sp[0]) ++;
    _1_fib_$pc[0] += 4;
    break;
    case _1_fib__PlusA_unsigned_int_unsigned_int2unsigned_int$left_STA_0$result_STA_0$right_STA_1: 
    (_1_fib_$pc[0]) ++;
    (_1_fib_$sp[0] + -1)->_unsigned_int = (_1_fib_$sp[0] + 0)->_unsigned_int + (_1_fib_$sp[0] + -1)->_unsigned_int;
    (_1_fib_$sp[0]) --;
    break;
    case _1_fib__branchIfTrue$expr_STA_0$label_LAB_0: 
    (_1_fib_$pc[0]) ++;
    if ((_1_fib_$sp[0] + 0)->_int) {
      _1_fib_$pc[0] += *((int *)_1_fib_$pc[0]);
    } else {
      _1_fib_$pc[0] += 4;
    }
    (_1_fib_$sp[0]) --;
    break;
    case _1_fib__constant_unsigned_int$result_STA_0$value_LIT_0: 
    (_1_fib_$pc[0]) ++;
    (_1_fib_$sp[0] + 1)->_unsigned_int = *((unsigned int *)_1_fib_$pc[0]);
    (_1_fib_$sp[0]) ++;
    _1_fib_$pc[0] += 4;
    break;
    case _1_fib__Le_unsigned_int_unsigned_int2int$right_STA_0$result_STA_0$left_STA_1: 
    (_1_fib_$pc[0]) ++;
    (_1_fib_$sp[0] + -1)->_int = (_1_fib_$sp[0] + -1)->_unsigned_int <= (_1_fib_$sp[0] + 0)->_unsigned_int;
    (_1_fib_$sp[0]) --;
    break;
    }
  }
}
}
